### Index
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2MzE1NDYxMTN9.NwVOWUoSVFgaoBdh38TdKrqaH8EWPHWfMMzZ3lvFtts
Content-Type: application/json

### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "TeBobst name",
  "email": "bob@test.com",
  "password": "password",
  "password_confirmation": "password"
}


### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "bob@test.com",
  "password": "password"
}

### Photos create
POST http://localhost:3000/photos
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjozLCJleHAiOjE2Mjk5OTI4NjR9.G2ExsrDYn3oE0vJkvm4T6Po2GbNpH5cqTEaVPVuK_MA
Content-Type: application/json

{
  "name": "Test name",
  "width": 640,
  "height": 480
}

